name=input("Hello my name is")
city=input()
favorite_color=input()
#print("Hello my name is",name)
print(name)
print("Iam from",city)
print("My favorite_color",favorite_color)
First_name=input()
Last_name=input()
print("Full Name:",First_name,Last_name)
#word=input()
#number=int()
#print(word*number)